// ============================================================
// 1. ВСЕ ИКОНКИ (ваш объект SKINGUIDE_ICONS)
// ============================================================
const SKINGUIDE_ICONS = {
  home: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M-11,1 L0,-10 L11,1" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/><path d="M-7,1 V10 H7 V1" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></g></svg>',
  skinProfile: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="0" cy="-6" r="4" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M-7,10 A7,9 0 0 1 7,10" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></g></svg>',
  planner: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><rect x="-9" y="-7" width="18" height="16" rx="2" fill="none" stroke="currentColor" stroke-width="1.8"/><line x1="-9" y1="-2" x2="9" y2="-2" stroke="currentColor" stroke-width="1.6"/><line x1="-4" y1="-10" x2="-4" y2="-7" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><line x1="4" y1="-10" x2="4" y2="-7" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><circle cx="-3" cy="4" r="1.2" fill="currentColor"/><circle cx="3" cy="4" r="1.2" fill="currentColor"/></g></svg>',
  shop: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M-7,-2 L-5,-9 H5 L7,-2 Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/><rect x="-7" y="-2" width="14" height="12" rx="2" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M-3,-9 Q0,-13 3,-9" fill="none" stroke="currentColor" stroke-width="1.6"/></g></svg>',
  blog: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><rect x="-7" y="-9" width="14" height="18" rx="1.5" fill="none" stroke="currentColor" stroke-width="1.8"/><line x1="-4" y1="-3" x2="4" y2="-3" stroke="currentColor" stroke-width="1.4"/><line x1="-4" y1="1" x2="4" y2="1" stroke="currentColor" stroke-width="1.4"/><line x1="-4" y1="5" x2="1" y2="5" stroke="currentColor" stroke-width="1.4"/></g></svg>',
  search: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="-2" cy="-2" r="6" fill="none" stroke="currentColor" stroke-width="1.8"/><line x1="2.2" y1="2.2" x2="8" y2="8" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></g></svg>',
  filter: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><line x1="-8" y1="-6" x2="8" y2="-6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/><line x1="-8" y1="0" x2="8" y2="0" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/><line x1="-8" y1="6" x2="8" y2="6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/><circle cx="-3" cy="-6" r="2" fill="currentColor"/><circle cx="4" cy="0" r="2" fill="currentColor"/><circle cx="-5" cy="6" r="2" fill="currentColor"/></g></svg>',
  theme: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M5,-8 A8,8 0 1 0 5,8 A6.2,6.2 0 1 1 5,-8 Z" fill="currentColor" stroke="none"/></g></svg>',
  language: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="0" cy="0" r="8" fill="none" stroke="currentColor" stroke-width="1.8"/><ellipse cx="0" cy="0" rx="8" ry="3" fill="none" stroke="currentColor" stroke-width="1.4"/><line x1="0" y1="-8" x2="0" y2="8" stroke="currentColor" stroke-width="1.4"/></g></svg>',
  recommended: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M0,-9 L2.6,-3 L9,-2.7 L3.8,1.6 L5.3,8 L0,4.3 L-5.3,8 L-3.8,1.6 L-9,-2.7 L-2.6,-3 Z" fill="currentColor" stroke="none"/></g></svg>',
  oily: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M0,-8 C4,-2 7,3 7,5 A7,7 0 1 1 -7,5 C-7,3 -4,-2 0,-8 Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></g></svg>',
  dry: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M0,-6 C3,-2 5,2 5,3.5 A5,5 0 1 1 -5,3.5 C-5,2 -3,-2 0,-6 Z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><line x1="-7" y1="7" x2="7" y2="-7" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></g></svg>',
  combination: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="0" cy="0" r="8" fill="none" stroke="currentColor" stroke-width="1.8"/><line x1="0" y1="-8" x2="0" y2="2" stroke="currentColor" stroke-width="1.6"/><line x1="-4" y1="-3" x2="4" y2="-3" stroke="currentColor" stroke-width="1.6"/></g></svg>',
  sensitive: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="0" cy="0" r="1.6" fill="currentColor"/><g fill="none" stroke="currentColor" stroke-width="1.6"><ellipse cx="0" cy="-5" rx="2.4" ry="4"/><ellipse cx="0" cy="5" rx="2.4" ry="4"/><ellipse cx="-5" cy="0" rx="4" ry="2.4"/><ellipse cx="5" cy="0" rx="4" ry="2.4"/></g></g></svg>',
  normal: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="0" cy="0" r="8" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="-3" cy="-2" r="1" fill="currentColor"/><circle cx="3" cy="-2" r="1" fill="currentColor"/><path d="M-3,3 Q0,5.5 3,3" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></g></svg>',
  acne: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="0" cy="0" r="2.4" fill="currentColor"/><circle cx="0" cy="0" r="7" fill="none" stroke="currentColor" stroke-width="1.4" stroke-dasharray="2 3"/></g></svg>',
  pigmentation: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="-3" cy="-2" r="2.6" fill="currentColor"/><circle cx="3" cy="1" r="1.8" fill="currentColor"/><circle cx="-1" cy="5" r="1.3" fill="currentColor"/></g></svg>',
  redness: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M0,-9 C4,-5 5,-1 3,2 C6,0 7,4 4,7 C6,8 3,9 0,9 C-4,9 -6,6 -5,3 C-7,4 -6,-1 -3,-3 C-4,-6 -2,-8 0,-9 Z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/></g></svg>',
  aging: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="0" cy="0" r="8" fill="none" stroke="currentColor" stroke-width="1.8"/><line x1="0" y1="0" x2="0" y2="-5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/><line x1="0" y1="0" x2="3.5" y2="1.5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></g></svg>',
  dryness: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M-7,-6 L-2,-1 L-5,1 L0,7 L3,0 L7,6" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></g></svg>',
  largePores: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><g fill="currentColor"><circle cx="-4" cy="-4" r="1"/><circle cx="0" cy="-4" r="1"/><circle cx="4" cy="-4" r="1"/><circle cx="-4" cy="0" r="1"/><circle cx="0" cy="0" r="1"/><circle cx="4" cy="0" r="1"/><circle cx="-4" cy="4" r="1"/><circle cx="0" cy="4" r="1"/><circle cx="4" cy="4" r="1"/></g></g></svg>',
  hydration: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M-2,-7 C0.5,-4 2.5,0 2.5,2 A4.5,4.5 0 1 1 -6.5,2 C-6.5,0 -4.5,-4 -2,-7 Z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><line x1="6" y1="-7" x2="6" y2="-3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/><line x1="4" y1="-5" x2="8" y2="-5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></g></svg>',
  brightening: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="0" cy="0" r="4" fill="none" stroke="currentColor" stroke-width="1.8"/><g stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><line x1="0" y1="-7" x2="0" y2="-9"/><line x1="5" y1="-5" x2="6.4" y2="-6.4"/><line x1="7" y1="0" x2="9" y2="0"/><line x1="5" y1="5" x2="6.4" y2="6.4"/><line x1="0" y1="7" x2="0" y2="9"/><line x1="-5" y1="5" x2="-6.4" y2="6.4"/><line x1="-7" y1="0" x2="-9" y2="0"/><line x1="-5" y1="-5" x2="-6.4" y2="-6.4"/></g></g></svg>',
  soothing: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M-6,7 C-6,-3 4,-9 9,-9 C9,-2 4,7 -6,7 Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/><line x1="-4" y1="5" x2="7" y2="-7" stroke="currentColor" stroke-width="1.3"/></g></svg>',
  sunProtection: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M-8,1 A8,7 0 0 1 8,1 Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/><line x1="0" y1="1" x2="0" y2="9" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/><path d="M0,9 Q3,10 3,7" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></g></svg>',
  budget: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="0" cy="0" r="7.5" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="0" cy="0" r="2" fill="currentColor"/></g></svg>',
  midRange: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><circle cx="-3" cy="2" r="6" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="3" cy="-3" r="6" fill="none" stroke="currentColor" stroke-width="1.7"/></g></svg>',
  premium: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><g transform="translate(12,12)"><path d="M-7,-3 L7,-3 L0,9 Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/><path d="M-4,-3 L0,2 L4,-3" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linejoin="round"/><line x1="-7" y1="-3" x2="7" y2="-3" stroke="currentColor" stroke-width="1.3"/></g></svg>',
};

// ============================================================
// 2. ФУНКЦИИ ДЛЯ РАБОТЫ С ИКОНКАМИ
// ============================================================

/**
 * Возвращает SVG-строку для указанного ключа.
 * Если ключа нет, возвращает пустую строку.
 */
function getIcon(name) {
  return SKINGUIDE_ICONS[name] || '';
}

/**
 * Заменяет все элементы с атрибутом data-icon на соответствующие SVG.
 * Вызывайте после загрузки DOM, например, внутри DOMContentLoaded.
 */
function renderIcons() {
  document.querySelectorAll('[data-icon]').forEach(el => {
    const key = el.getAttribute('data-icon');
    const svg = getIcon(key);
    if (svg) {
      el.innerHTML = svg;
      // Удаляем атрибут, чтобы не обрабатывать повторно
      el.removeAttribute('data-icon');
    } else {
      // Можно оставить как есть или показать предупреждение
      console.warn('Icon not found:', key);
    }
  });
}
